source 'https://rubygems.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development do
  # make 'rails console' use pry instead of irb
  # this also lets us use 'binding.pry'
  gem 'pry-rails'

  # gives us the ability to step through our code when using pry
  gem 'pry-byebug'

  # fancy pants rails error messages with REPL in the browser
  gem 'better_errors'
  gem 'binding_of_caller'

  # required for 'rails panel' chrome extension
  # for sublime support install app: https://github.com/exalted/sublimetext-launcher
  gem 'meta_request'
end